version: '3'
services:
  db:
    image: postgres:latest
    container_name: social_media
    ports:
      - '6500:5432'
    volumes:
      - postgresDB:/data/postgres
    env_file:
      - ./.env.docker
volumes:
  postgresDB:
